### ISSUE TITLE
`.npmignore`

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#4]
`.npmignore` is used, but why?

**Comment by Zishrodrigues** [comment]
My research has shown me that using .npmignore with '!.env' allows one to deploy a project to Zeit now whilst using a .env file to hide secrets. 

Is that a correct way to go about it?

**Comment by wooorm** [comment]
Doesn’t that expose your `.env` file on Now? I think it’s better to use the [built in secrets mechanism](https://zeit.co/blog/environment-variables-secrets)!

**Comment by Zishrodrigues** [comment]
Turned out to not need .env for this project so I removed the ununsed package, aswell as the .env and .npmignore file.

Feedback has been noted and i'll be using the built in secrets mechanism for my next project.

https://github.com/Zishrodrigues/meesterproef/commit/16d7adf8fbb2928362037bb4334eb4d6cff51d9c
